# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: CI

on:
  pull_request:
  push:
    branches:
      master
    tags:
      - '*'

jobs:
  lint:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v2.0.2
      - name: yarn install
        run: yarn --frozen-lockfile --install
      - name: lint
        run: yarn lint

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v2.0.2
      - name: yarn install
        run: yarn --frozen-lockfile --install
      - name: test
        run: yarn test:jest

  test-node:
    name: 'node:${{matrix.node}}:${{matrix.os}}' # rely on matrix for most of name
    needs: [lint, test]
    runs-on: "${{matrix.os}}-latest"

    strategy:
      fail-fast: false
      matrix:
        node: [12.x, 14.x, 16.x] # LTS + current
        os: [ubuntu, macOS, windows]

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v2.0.2
        with:
          node-version: ${{matrix.node}}
      - name: yarn install
        run: yarn --frozen-lockfile --install
      - name: test
        run: yarn test:jest
